/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KeyRecovery } from "./KeyRecovery";

export { KeyRecovery__factory } from "./factories/KeyRecovery__factory";
